version: "3.7"
# образ сервиса подтягивается из реджистри

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-docker-config.yaml:/etc/otelcol-contrib/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GRAFANA_CLOUD_OTLP_ENDPOINT: "https://otlp-gateway-prod-us-east-0.grafana.net/otlp"
      GRAFANA_CLOUD_INSTANCE_ID: "${GRAFANA_CLOUD_INSTANCE_ID}"
      GRAFANA_CLOUD_API_KEY: "${GRAFANA_CLOUD_API_KEY}"
    networks:
      - default

  mysql:
    image: mysql:8.0.31-debian
    container_name: mysql_rsse
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_USER=1
      - MYSQL_PASSWORD=1
      - MYSQL_DATABASE=tagit
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    expose:
      - 3306
    volumes:
      - compose-mysql-volume:/var/lib/mysql
    networks:
      - default

  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres_rsse
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: 1
      POSTGRES_DB: tagit
    expose:
      - 5432
    volumes:
      - compose-pg-volume:/var/lib/postgresql/data
    networks:
      - default

  tagit:
    # образ билдится при деплое в k3s:
    # image: nick219nick/rsse-app:latest
    # образ билдится по тегу `dx.x.x` либо крону:
    image: ghcr.io/nicks219/rssearchengine:latest
    container_name: rsse
    depends_on:
      otel-collector:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: always
    environment:
      OTEL_RESOURCE_ATTRIBUTES="service:name=rsse-app,service:namespace=rsse-group,deployment:environment=production":
    ports:
      - 5100:5000
    networks:
      - default

volumes:
  compose-mysql-volume:
  compose-pg-volume:
